### ISSUE TITLE
The purpose of collecting the weather data.

### ISSUE THREAD

**Issue by Manuel4131** [OpenHackFarm/CODiS_carwler#2]
Hi, I have some questions listed here:
1. What kind of weather data do we need? (Temperature, humidity and ?)
2. Since the farm locates at Ilan, do we still need the data from all the places in Taiwan?
3. What's the `major` purpose of collecting these data? How can we utilize the data in helping the crop? 
Thanks!

**Comment by a0726h77** [comment]
爲了配合生產記錄分析，我們必須與氣象資料做對應。

而且，必須讓各地農民都有方便的氣象儀表板可以使用，我們資料來源可能來自各政府機關、或是學校等民間自架的氣象站。

**Comment by Manuel4131** [comment]
Ok, thanks for the explanation.
